name: Build Changelog

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-changelog:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Action / Setup GO
        uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.18.3'

      - name: git-chglog / Download
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: git-chglog / Update CHANGELOG.md
        run: |
          git-chglog -o CHANGELOG.md

      - name: git-chglog / Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'docs: updated CHANGELOG.md'
          file_pattern: 'CHANGELOG.md'
          push_options: '--force'
          branch: 'main'
